ra_analyze.lo: ra_analyze.fpp ra_option_str_mod.mod
ra_analyze_mod.mod: ra_analyze.fpp ra_analyze.lo
ra_control.lo: ra_control.fpp ra_option_mod.mod
ra_control_mod.mod: ra_control.fpp ra_control.lo
ra_main.lo: ra_main.fpp ra_option_str_mod.mod ra_control_mod.mod ra_analyze_mod.mod ra_setup_mod.mod
ra_option.lo: ra_option.fpp ra_option_str_mod.mod
ra_option_mod.mod: ra_option.fpp ra_option.lo
ra_option_str.lo: ra_option_str.fpp
ra_option_str_mod.mod: ra_option_str.fpp ra_option_str.lo
ra_setup.lo: ra_setup.fpp ra_control_mod.mod ra_option_str_mod.mod ra_option_mod.mod
ra_setup_mod.mod: ra_setup.fpp ra_setup.lo
